src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $reservation_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $return_date = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Book $book = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $student = null;

    #[ORM\ManyToOne(inversedBy: 'validated_reservations')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $validator = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReservationDate(): ?\DateTimeInterface
    {
        return $this->reservation_date;
    }

    public function setReservationDate(\DateTimeInterface $reservation_date): static
    {
        $this->reservation_date = $reservation_date;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(\DateTimeInterface $return_date): static
    {
        $this->return_date = $return_date;

        return $this;
    }


    public function getBookId(): ?Book
    {
        return $this->book;
    }

    public function setBookId(?Book $book): static
    {
        $this->book = $book;

        return $this;
    }

    public function getStudent(): ?User
    {
        return $this->student;
    }

    public function setStudent(?User $student): static
    {
        $this->student = $student;

        return $this;
    }

    public function getValidator(): ?User
    {
        return $this->validator;
    }

    public function setValidator(?User $validator): static
    {
        $this->validator = $validator;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): void
    {
        $this->book = $book;
    }

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\Reservation;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reservation_date', null, [
                'widget' => 'single_text',
            ])
            ->add('return_date', null, [
                'widget' => 'single_text',
            ])
            ->add('book', EntityType::class, [
                'class' => Book::class,
                'choice_label' => 'name',
            ])
            ->add('student', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'email',
            ])
            ->add('validator', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_show', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository, Security $security): Response
    {

        $user = $security->getUser();
        $role = $user ? $user->getRoles()[0] : null;

        if ($role === 'ROLE_ADMIN') {
            $reservations = $reservationRepository->findAll();
        } elseif ($role === 'ROLE_STUDENT') {
            $reservations = $user->getReservations();
        } else {
            throw $this->createAccessDeniedException('Unauthorized access');
        }
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservations,
        ]);
    }


    #[IsGranted("ROLE_ADMIN")]
    #[Route('/validateReservation/{idR}', name: 'app_reservation_validation', methods: ['GET', 'POST'])]
    public function validate(Reservation $idR, Request $request, EntityManagerInterface $entityManager): Response
    {

        $idR->setValidator($this->getUser());
        $entityManager->persist($idR);
        $entityManager->flush();
        return $this->redirectToRoute('app_reservation_show');
    }

}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reservation_date</th>
                <th>Return_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.reservationDate ? reservation.reservationDate|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.returnDate ? reservation.returnDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('app_reservation_validation', {'idR': reservation.id}) }}">validate</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Reservation_date</th>
                <td>{{ reservation.reservationDate ? reservation.reservationDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Return_date</th>
                <td>{{ reservation.returnDate ? reservation.returnDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}